### ISSUE TITLE
The route list logger needs to extra option to ignore log the list 

### ISSUE THREAD

**Issue by pharzam** [arashmilani/xpress-router#3]
**Current Behavior**: Xpress router logs the list of routes for every call of `Xpress` router if the ENV is `development`. 
**The real situation** is if we use the Xpress router for some other layer of middleware for any purpose like permission-checker and controller,  the Xpress logs twice instead of once in development mode
**The expected behavior** is, There must be an extra option for logging routes list in development mode that its default value must be true.

the pattern of current route for third parameter is like this 
 
```
options:{
   controllerDirectory: '/directory',
   controllerFileSuffix: 'controller-prefix'
}

```

the pattern will be should be like this
```
options:{
   controllerDirectory: '/directory',
   controllerFileSuffix: 'controller-prefix',
   doesLogTheRoute : true
}
```

**Comment by arashmilani** [comment]
Thank you @pharzam for the PR. It has been merged to master.
